### ISSUE TITLE
Linux ARM version for tableplus

### ISSUE THREAD

**Issue by JeanRomain** [TablePlus/TablePlus-Linux#112] opened 2021-04-22 19:58 UTC
Hello,
An ARM version can be useful to run on virtualized linux on M1 Macs
Thanks guys

**Comment by baarkerlounger** [comment] 2021-04-28 10:49
Duplicate of https://github.com/TablePlus/TablePlus-Linux/issues/69 ?

**Comment by JeanRomain** [comment] 2021-04-28 13:59
I think yes since it's a virtualized ARM64 Linux on a ARM64 processor

**Comment by huyphams** [comment] 2023-03-01 15:26
I've built a `aarch64` version of TablePlus Linux but I'm not sure if I should publish it or not. Why do you want to use it on virtual machine instead of macOS @JeanRomain ?

<img width="1154" alt="Screenshot 2023-03-01 at 10 24 40 PM" src="https://user-images.githubusercontent.com/3654622/222184759-8e493b42-17c0-407b-b4db-bebc28f8b2fa.png">

**Comment by elalecs** [comment] 2023-03-01 15:46
That build works for me to use it in a Raspberry Pi and in a remote Linux desktop over a cloud, please share it!

**Comment by elalecs** [comment] 2023-03-01 17:21
Debian 🙏

**Comment by huyphams** [comment] 2023-03-03 04:43
You may want to try the build at:

```
# Add TablePlus gpg key
wget -qO - https://deb.tableplus.com/apt.tableplus.com.gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/tableplus-archive.gpg > /dev/null

# Add TablePlus repo
sudo add-apt-repository "deb [arch=arm64] https://deb.tableplus.com/debian/22-arm tableplus main"

# Install
sudo apt update
sudo apt install tableplus
```

**Comment by huyphams** [comment] 2023-03-03 04:45
Please also install those packages if they are missing:
```
 sudo apt install libssh-dev libpq-dev
```

**Closed** 2023-03-03 16:26 UTC

**Comment by tkayo** [comment] 2024-01-14 08:36
@huyphams i just tried the above and seemed to install but attempting to open on the latest Raspberry Pi OS didn't open
