### ISSUE TITLE
TablePlus doesn't start on Manjaro

### ISSUE THREAD

**Issue by skatkov** [TablePlus/TablePlus-Linux#121] opened 2021-07-27 08:30 UTC
1. Database version (Ex: PostgreSQL 10.0):
Pg 13

2. TablePlus version (the number on the welcome or about screen, Ex: build 81):
0.1.84

3. Linux distro (Ex: Ubuntu 18.04): 
Manjaro
4. The steps to reproduce this issue:
Try to start an app

## Result
Nothing is shown. Here is an error I've found:
tableplus: /usr/lib/libldap_r-2.4.so.2: no version information available (required by tableplus)

**Comment by theonaciri** [comment] 2021-08-10 08:01
Hi, I'm on Manjaro too, you can download it from the AUR [](https://aur.archlinux.org/packages/tableplus/) and install it with `makepkg -si`. It works on my machine.

**Comment by PHLAK** [comment] 2021-08-18 18:55
I've been having the same issue on Arch. After booting my PC I can usually start Tableplus once. However, if I close it and attempt to run a new instance from the app icon it does not open. After attempting to run it I can see processes present (one for each time I tried to start it from the app icon).

```
$ ps ax | grep tableplus
  80184 ?        SLl    0:00 /usr/local/bin/tableplus
  80378 ?        SLl    0:00 /usr/local/bin/tableplus
  80390 pts/1    S+     0:00 grep --color=auto tableplus
```

Even if I kill these "zombie" processes (`killall -9 tableplus`) am still unable to launch the app from the app icon. However, I _can_ run it from the command line (and get the UI) with the same error/warning @theonaciri mentioned.

```
$ tableplus 
tableplus: /usr/lib/libldap_r-2.4.so.2: no version information available (required by tableplus)
```

**Comment by PHLAK** [comment] 2021-08-18 18:56
May be related to #116

**Comment by gorbak25** [comment] 2021-09-10 16:11
Same here

**Comment by olielvewen** [comment] 2021-10-06 14:03
Since the last update, Tableplus doesn't work on Manjaro. This error is the same that @theonaciri and @phlax. 

I've got an update today and it is exactly the same thing.

```
[olivier@thorielle ~]$ tableplus
tableplus: /usr/lib/libldap_r-2.4.so.2: no version information available (required by tableplus)
Erreur de segmentation (core dumped)
[olivier@thorielle ~]$ pacman  -Qi libldap
Nom                      : libldap
Version                  : 2.4.59-2
Description              : Lightweight Directory Access Protocol (LDAP) client libraries
Architecture             : x86_64
URL                      : https://www.openldap.org/
Licences                 : custom
Groupes                  : --
Fournit                  : --
Dépend de                : libsasl  e2fsprogs
Dépendances opt.         : --
Requis par               : gconf  krb5  lib32-libldap  nfsidmap  postgresql-libs  smbclient  sudo
Optionnel pour           : apr-util  gnupg
Est en conflit avec      : --
Remplace                 : --
Taille installée         : 934,93 KiB
Paqueteur                : Antonio Rojas <arojas@archlinux.org>
Compilé le               : dim. 18 juil. 2021 22:59:35
Installé le              : ven. 30 juil. 2021 23:07:45
Motif d’installation     : Installé comme dépendance d’un autre paquet
Script d’installation    : Non
Validé par               : Signature
[olivier@thorielle ~]$ pacman -Qi tableplus
Nom                      : tableplus
Version                  : 0.1.176-1
Description              : Modern, native, and friendly GUI tool for relational databases (Alpha)
Architecture             : x86_64
URL                      : https://tableplus.com/
Licences                 : custom
Groupes                  : --
Fournit                  : --
Dépend de                : gtksourceview3  libgee  gnome-keyring
Dépendances opt.         : --
Requis par               : --
Optionnel pour           : --
Est en conflit avec      : --
Remplace                 : --
Taille installée         : 44,34 MiB
Paqueteur                : Unknown Packager
Compilé le               : mer. 06 oct. 2021 15:41:30
Installé le              : mer. 06 oct. 2021 15:41:45
Motif d’installation     : Explicitement installé
Script d’installation    : Non
Validé par               : --

```

I hope that will help you for resolving this annoying issue. Especially that Tableplus was working really great until now.

**Comment by theonaciri** [comment] 2021-10-08 07:49
The error seems explicit. Do you have lib32-libldap on your machine ? Personally I do and it works on my device.

Install it manually : `pacman -S lib32-libldap`
Checkout this link for other platforms than Manjaro: [https://www.codeweavers.com/support/wiki/Diag/MissingLibLdap_r](https://www.codeweavers.com/support/wiki/Diag/MissingLibLdap_r)

**Comment by wiktorglowacki** [comment] 2021-12-30 19:41
@davincible

Did you manage to run in on Manjaro?
After the latest AUR update I'm getting:

`tableplus: error while loading shared libraries: libldap-2.5.so.0: cannot open shared object file: No such file or directory`

**Comment by Davincible** [comment] 2021-12-30 20:04
@wiktorglowacki unfortunately not

**Comment by olielvewen** [comment] 2021-12-30 20:38
@wiktorglowacki  Me too, unfortunately not even with the last update there are few days ago.

**Comment by skatkov** [comment] 2021-12-30 21:17
I'm on a fresh install of Manjaro, still can't run TablePlus unfortunately.

**Comment by PabloSzx** [comment] 2022-02-17 19:44
no workaround?

**Comment by FilipeAdao96** [comment] 2022-03-12 19:45
Still not workaround?

**Comment by wiktorglowacki** [comment] 2022-03-13 09:16
@FilipeAdao96 Not at all :/ There was an update today but it did not help.

@huyphams any chance to get that fixed?

**Comment by eboye** [comment] 2022-03-24 04:13
Same here, tried it a month ago and now with this new version, but libldap error is still here.

I wish there was flatpak or appimage version to overcome this dependency problem :(

**Comment by huyphams** [comment] 2022-03-24 04:52
The libldap has nothing to do with this error. It is just a warning. Please use the correct repo and you will be able to open the app on Manjaro.

There are 3 repos, I think the one which is built for Ubuntu 20 (or 21) will work on Manjaro.

**Comment by huyphams** [comment] 2022-03-24 04:54
Libldap is a PostgreSQL authentication extension and it is a dynamic library. You only need this lib when you connect to a PostgreSQL instance with an LDAP authenticator. TablePlus does not support this anyway but it is a part of the driver so there is no way to exclude it. So it is just a warning and it will not affect the app.

**Comment by huyphams** [comment] 2022-03-24 05:00
On Ubuntu 20.04,  I don't have that file but the app still working
<img width="357" alt="Screen Shot 2022-03-24 at 11 59 33 AM" src="https://user-images.githubusercontent.com/3654622/159845538-f1b3a6bb-020a-4b11-a451-a44853a09a86.png">

**Comment by wiktorglowacki** [comment] 2022-03-24 06:43
@huyphams It would be great if you can point us to the repo that will work on Manjaro. I'm registered user on OSX but I would really love to have TablePlus back working on Manjaro.

**Comment by huyphams** [comment] 2022-03-24 08:30
I  think I found the root cause, there are many other missing libs (due to different loading paths). Let me see if I can bundle those libs into the app or static link them.

**Comment by eboye** [comment] 2022-03-25 00:53
If you know all the deps needed it would be great if you could list them here or somewhere. I've successfully made few appimages in the past using this tool, but since I don't know the exact config I should be making, as it's not open source project, I lack some info.

https://github.com/simoniz0r/deb2appimage

**Comment by hparadiz** [comment] 2022-04-19 19:55
I'm having this issue on Gentoo as well. I even specifically installed OpenLDAP 2.4 and still having issues

```
~ $ ls -l /usr/lib64/ | grep ldap
lrwxrwxrwx   1 root   root         21 Apr 18 18:10 libldap-2.4.so.2 -> libldap-2.4.so.2.11.6
-rwxr-xr-x   1 root   root     326488 Apr 18 18:10 libldap-2.4.so.2.11.6
-rw-r--r--   1 root   root     631318 Apr 18 18:10 libldap.a
-rw-r--r--   1 root   root        971 Apr 18 18:10 libldap.la
lrwxrwxrwx   1 root   root         23 Apr 18 18:10 libldap_r-2.4.so.2 -> libldap_r-2.4.so.2.11.6
-rwxr-xr-x   1 root   root     347544 Apr 18 18:10 libldap_r-2.4.so.2.11.6
-rw-r--r--   1 root   root     676176 Apr 18 18:10 libldap_r.a
-rw-r--r--   1 root   root        985 Apr 18 18:10 libldap_r.la
lrwxrwxrwx   1 root   root         23 Apr 18 18:10 libldap_r.so -> libldap_r-2.4.so.2.11.6
lrwxrwxrwx   1 root   root         21 Apr 18 18:10 libldap.so -> libldap-2.4.so.2.11.6
```

```
tableplus: /usr/lib64/libldap_r-2.4.so.2: no version information available (required by tableplus)
```

**Comment by blue7wings** [comment] 2022-05-09 00:56
Hi, all 
the problem has been fixed by using this script from the latest comment in [https://aur.archlinux.org/packages/tableplus](https://aur.archlinux.org/packages/tableplus)
```
git clone https://aur.archlinux.org/tableplus.git
cd tableplus
wget https://gist.githubusercontent.com/hpsu/49f2162bd9ded9c97e0c201065345189/raw/8ff143c6432c485824196a36c5a329afcbd52089/tableplus-dependencies.patch
git apply tableplus-dependencies.patch
makepkg -si
```

**Comment by Davincible** [comment] 2022-05-09 10:46
@blue7wings running commands as you provided doesn't fix it for me on Manjaro

**Comment by skatkov** [comment] 2022-05-10 08:17
@Davincible I've managed to get it working with @blue7wings recommendations, just required a restart :)

**Comment by Davincible** [comment] 2022-05-10 09:00
@skatkov I still get 
`tableplus: error while loading shared libraries: libldap-2.5.so.0: cannot open shared object file: No such file or directory`

And `fd libldap /usr` returns:
```
/usr/lib32/libldap.so
/usr/lib/libldap.so
/usr/lib/libldap.so.2.0.200
/usr/lib64/libldap.so.2.0.200
/usr/lib/libldap.so.2
/usr/lib64/libldap.so.2
/usr/lib64/libldap.so
/usr/lib64/thunderbird/libldap60.so
/usr/lib/thunderbird/libldap60.so
/usr/lib32/libldap.so.2.0.200
/usr/lib32/libldap.so.2
/usr/share/licenses/lib32-libldap
/usr/share/licenses/libldap
```
What does your fd return now?

**Comment by wiktorglowacki** [comment] 2022-05-11 18:19
@alariva @Davincible Works well from CLI with command:

`/usr/bin/env LD_PRELOAD=/opt/tableplus/lib/libldap-2.5.so.0.1.1:/opt/tableplus/lib/liblber-2.5.so.0.1.1:/opt/tableplus/lib/libsasl2.so.2.0.25:/opt/tableplus/lib/libgio-2.0.so.0.6800.4 /usr/local/bin/tableplus`

**Comment by alariva** [comment] 2022-05-11 18:21
@wiktorglowacki  you'r right thanks for the hint!

![image](https://user-images.githubusercontent.com/3021314/167919243-6ac29157-f499-4a64-8d73-de1d431a1592.png)

**Comment by MyFRA** [comment] 2022-06-03 02:04
@blue7wings thanks. It works for me

**Comment by umegbewe** [comment] 2022-06-08 16:44
@blue7wings works for me. Thanks

**Comment by PetrusZ** [comment] 2022-06-10 16:59
Maybe TablePlus can release a appImage version like navicat, so it can save all the troubles caused by the incompatible library.

**Comment by eboye** [comment] 2022-06-11 00:26
> Maybe TablePlus can release a appImage version like navicat, so it can save all the troubles caused by the incompatible library.

+1 for that. AppImage and flatpak are my favorite. AppImage especially

**Comment by JulianKarhof** [comment] 2022-09-01 11:19
@blue7wings this seems to be broken now as the ubuntu archive links just lead to a 404. I tried substituting with packages in a similar version range but that doesn't seem to have worked.

**Comment by huyphams** [comment] 2022-09-14 05:45
TablePlus for Ubuntu 18, 20, 21, and the latest 22.04 has been updated. If you have a chance, please give it a try!
TablePlus for Ubuntu 22.04 has a different repo, please see
https://tableplus.com/linux/install

**Closed by huyphams** 2022-09-14 05:45 UTC

**Comment by eboye** [comment] 2022-09-14 23:35
still missing those libs

**Comment by huyphams** [comment] 2022-09-16 14:09
> Even if I kill these "zombie" processes (killall -9 tableplus) am still unable to launch the app from the app icon. However, I can run it from the command line (and get the UI) with the same error/warning @theonaciri mentioned.


Hi @PHLAK I believe the build 192 has addressed the issue.

**Comment by lethehoa** [comment] 2022-12-05 06:57
[https://i.imgur.com/F4vjCy6.png](url)

I got the same problem with ver 0.1.192. I'm using Manjaro. I still working around but haven't found any solution yet.

**Comment by eboye** [comment] 2022-12-05 22:45
This is my working version. This is a git diff from the aur.

```diff
diff --git a/PKGBUILD b/PKGBUILD
index 4384d1e..4893225 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -2,7 +2,7 @@
 # Maintainer: Henry Pham <huy at tableplus dot com>
 
 pkgname=tableplus
-pkgver=0.1.188
+pkgver=0.1.192
 pkgrel=2
 pkgdesc='Modern, native, and friendly GUI tool for relational databases (Alpha)'
 arch=('x86_64')
@@ -18,11 +18,11 @@ source=('LICENSE'
 noextract=("libldap-2.5-0_2.5.11+dfsg-1~exp1ubuntu3_amd64.deb"
            "libsasl2-2_2.1.27+dfsg2-3ubuntu1_amd64.deb")
 sha256sums=('76f924b1ebad5309ccf0dd7f3fe3d1b57ff3088b208a603900b0e240fdb5debb'
-            'c8ede03457eb84ce7c617b7a5f88a5254905e3d96405f318d43a0fec08577bd8'
+            'b7afa94ab139d7e493fc778a65270b4f5f3b83bbacc53ffd439f4c4753b29d4b'
             'f28638149498d6fbac35ee3f9f11ad399953b2a9ba1a47ca457dce39f091ba0b'
             'e68ac6059677e0356e492e0e6a6c31344a4815f03e7cf367fe35fe1e7ebc128c'
             'e8e759bd9abb58c93067e199088077f3d6fa2c608ebc6f571cb9dd814812bcea'
-            'e3dedf8c93e5a8966eb3d5c1f25071a0e6d049279be0149cfb6280c9674d6f6f')
+            '3cb8382dad6ca3cc1d966391c217fa6011f80dd4c84d9fe52b55fb2efd2c450d')
 
 prepare() {
     tar -xf "${srcdir}/data.tar.zst"
```

**Comment by lethehoa** [comment] 2022-12-08 03:59
https://aur.archlinux.org/packages/tableplus#comment-865285

I followed those step, it worked!!

**Comment by lethehoa** [comment] 2022-12-08 04:00
> @lethehoa yes, this is got cloned the PKGBUILD from AUR and m

Thanks for your respond
